### ISSUE TITLE
All the sizes are int and should be size_t type

### ISSUE THREAD

**Issue by jeromelebel** [mongodb/libbson#67]
I think that's horrible to use int32_t for sizes (for strings, keys and other...). I understand bson are limited to ((1U << 31) - 1). But that's an implementation problem. I think the API should use size_t.

There are a lot of cast from size_t to int32_t in the code (for example every time bson_append_utf8 is called since key_length and length are in int32_t). The problem is that each time I'm doing a cast like that, I'm responsible to make sure my value can be cast. And this is really annoying.
It would be nicer to have all the APIs with size_t, since the code is there to make sure the bson never exceed ((1U << 31) - 1).

I don't mind doing a pull request with those modification. But I just want to make sure I can convince you, before working on that.

Let me know if you agree with this idea, and if you prefer to do it, or you prefer I do it.

Thanks

**Comment by samantharitter** [comment]
Hi @jeromelebel, it looks like this discussion and your pull request fell by the wayside.  I'm not sure if we'd still be willing to break ABI at this point, I'll have to discuss with @hanumantmk.  In the mean time I've opened a [ticket for this in the C driver's JIRA project](https://jira.mongodb.org/browse/CDRIVER-517), and we'll continue addressing this on there.  I'm going to close the issue here on github.  Thanks!
